#!/usr/bin/python3

import os
import sys
import argparse
import re
from typing import List, Dict, Tuple, Optional
from dataclasses import dataclass
from enum import Enum, auto

class PropertyType(Enum):
    STRING = auto()
    INT32 = auto()
    UINT32 = auto()
    FLOAT64 = auto()
    BOOLEAN = auto()
    OBJECT = auto()

@dataclass
class Property:
    name: str
    prop_type: PropertyType
    rust_type: str
    default_value: str

@dataclass
class Signal:
    name: str
    params: List[Tuple[str, str]]  # List of (param_name, param_type)
    return_type: Optional[str] = None

class RustGObjectGenerator:
    VALID_IDENTIFIER = re.compile(r'^[A-Za-z][A-Za-z0-9_]*$')
    VALID_CLASSNAME = re.compile(r'^[A-Z][A-Za-z0-9]*$')
    
    TYPE_MAPPING = {
        'string': (PropertyType.STRING, 'String', '""'),
        'str': (PropertyType.STRING, 'String', '""'),
        'i32': (PropertyType.INT32, 'i32', '0'),
        'u32': (PropertyType.UINT32, 'u32', '0'),
        'f64': (PropertyType.FLOAT64, 'f64', '0.0'),
        'bool': (PropertyType.BOOLEAN, 'bool', 'false'),
        'boolean': (PropertyType.BOOLEAN, 'bool', 'false'),
    }

    def __init__(self):
        self.imp_template = '''// Generated by RustGObjectGenerator
// This file is licensed under the same terms as the project it belongs to

use glib::prelude::*;
use glib::subclass::prelude::*;
use glib::subclass::Signal;
use glib::Properties;
use std::cell::RefCell;
use std::sync::OnceLock;
{additional_imports}

mod imp {{
    use super::*;

    #[derive(Properties, Default)]
    #[properties(wrapper_type = super::{class_name})]
    pub struct {class_name} {{
{properties}
    }}

    #[glib::derived_properties]
    impl ObjectImpl for {class_name} {{
        fn constructed(&self) {{
            self.parent_constructed();
            let obj = self.obj();
            // Initialize default state here if needed
        }}

        fn signals() -> &'static [Signal] {{
            static SIGNALS: OnceLock<Vec<Signal>> = OnceLock::new();
            SIGNALS.get_or_init(|| vec![
{signals}
            ])
        }}
    }}

    #[glib::object_subclass]
    impl ObjectSubclass for {class_name} {{
        const NAME: &'static str = "{class_name}";
        type Type = super::{class_name};
        type ParentType = {parent_class};
    }}
}}

glib::wrapper! {{
    pub struct {class_name}(ObjectSubclass<imp::{class_name}>);
}}

impl {class_name} {{
    pub fn new() -> Self {{
        glib::Object::builder()
{property_defaults}
            .build()
    }}

    pub fn new_with_params({constructor_params}) -> Self {{
        glib::Object::builder()
{property_builders}
            .build()
    }}

{additional_methods}
}}

// Implement Debug trait
impl std::fmt::Debug for {class_name} {{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {{
        f.debug_struct("{class_name}")
{debug_fields}
            .finish()
    }}
}}'''

    def validate_class_name(self, name: str) -> bool:
        """Validate class name follows Rust naming conventions."""
        return bool(self.VALID_CLASSNAME.match(name))

    def validate_identifier(self, name: str) -> bool:
        """Validate identifier follows Rust naming conventions."""
        return bool(self.VALID_IDENTIFIER.match(name))

    def parse_property(self, prop_str: str) -> Property:
        """Parse property string into Property object with validation."""
        try:
            name, type_str = prop_str.split(':')
            
            if not self.validate_identifier(name):
                raise ValueError(f"Invalid property name: {name}")
            
            type_str = type_str.lower()
            if type_str not in self.TYPE_MAPPING:
                if type_str.endswith('object'):
                    # Handle GObject types
                    return Property(
                        name=name,
                        prop_type=PropertyType.OBJECT,
                        rust_type=type_str.replace('object', 'Object'),
                        default_value='None'
                    )
                raise ValueError(f"Unsupported type: {type_str}")
            
            prop_type, rust_type, default_value = self.TYPE_MAPPING[type_str]
            return Property(name=name, prop_type=prop_type, rust_type=rust_type, default_value=default_value)
            
        except ValueError as e:
            raise ValueError(f"Invalid property format. Expected 'name:type', got '{prop_str}'. {str(e)}")

    def parse_signal(self, signal_str: str) -> Signal:
        """Parse signal string into Signal object with validation."""
        try:
            if '(' in signal_str:
                # Signal with parameters
                name, params_str = signal_str.split('(', 1)
                params_str = params_str.rstrip(')')
                params = []
                
                if params_str:
                    for param in params_str.split(','):
                        param = param.strip()
                        if ':' in param:
                            param_name, param_type = param.split(':')
                            if not self.validate_identifier(param_name):
                                raise ValueError(f"Invalid parameter name: {param_name}")
                            params.append((param_name, param_type))
                        else:
                            raise ValueError(f"Invalid parameter format: {param}")
                
                if not self.validate_identifier(name):
                    raise ValueError(f"Invalid signal name: {name}")
                    
                return Signal(name=name, params=params)
            else:
                # Simple signal without parameters
                if not self.validate_identifier(signal_str):
                    raise ValueError(f"Invalid signal name: {signal_str}")
                return Signal(name=signal_str, params=[])
                
        except ValueError as e:
            raise ValueError(f"Invalid signal format. Expected 'name(param:type,...)' or 'name', got '{signal_str}'. {str(e)}")

    def generate_properties_code(self, properties: List[Property]) -> str:
        """Generate Rust code for properties."""
        prop_lines = []
        for prop in properties:
            if prop.prop_type == PropertyType.OBJECT:
                prop_lines.append(f'        #[property(get, set)]\n        {prop.name}: RefCell<Option<{prop.rust_type}>>,')
            else:
                prop_lines.append(f'        #[property(get, set)]\n        {prop.name}: RefCell<{prop.rust_type}>,')
        return '\n'.join(prop_lines) if prop_lines else '        // No properties defined'

    def generate_signals_code(self, signals: List[Signal]) -> str:
        """Generate Rust code for signals."""
        signal_lines = []
        for signal in signals:
            if signal.params:
                params_str = ', '.join(f'("{name}", {type_})' for name, type_ in signal.params)
                signal_lines.append(f'                Signal::builder("{signal.name}")\n'
                                 f'                    .param_types([{params_str}])\n'
                                 f'                    .build(),')
            else:
                signal_lines.append(f'                Signal::builder("{signal.name}").build(),')
        return '\n'.join(signal_lines) if signal_lines else '                // No signals defined'

    def generate_additional_methods(self, properties: List[Property], signals: List[Signal]) -> str:
        """Generate additional helper methods."""
        methods = []
        
        # Generate signal emission methods
        for signal in signals:
            params_str = ', '.join(f'{name}: {type_}' for name, type_ in signal.params)
            method_name = f"emit_{signal.name}"
            if params_str:
                methods.append(f'''    pub fn {method_name}(&self, {params_str}) {{
        self.emit_by_name::<()>("{signal.name}", &[{', '.join(n for n, _ in signal.params)}]);
    }}''')
            else:
                methods.append(f'''    pub fn {method_name}(&self) {{
        self.emit_by_name::<()>("{signal.name}", &[]);
    }}''')

        return '\n\n'.join(methods)

    def generate_code(self, class_name: str, parent_class: str, 
                     properties: List[str], signals: List[str], 
                     additional_imports: Optional[List[str]] = None) -> str:
        """Generate complete Rust code for the GObject class."""
        try:
            if not self.validate_class_name(class_name):
                raise ValueError(f"Invalid class name: {class_name}")

            # Parse properties and signals
            parsed_properties = [self.parse_property(prop) for prop in properties]
            parsed_signals = [self.parse_signal(signal) for signal in signals]

            # Generate the code
            return self.imp_template.format(
                class_name=class_name,
                parent_class=parent_class,
                additional_imports='\n'.join(additional_imports or []),
                properties=self.generate_properties_code(parsed_properties),
                signals=self.generate_signals_code(parsed_signals),
                property_defaults=self.generate_property_defaults(parsed_properties),
                constructor_params=self.generate_constructor_params(parsed_properties),
                property_builders=self.generate_property_builders(parsed_properties),
                additional_methods=self.generate_additional_methods(parsed_properties, parsed_signals),
                debug_fields=self.generate_debug_fields(parsed_properties)
            )
        except Exception as e:
            raise RuntimeError(f"Error generating code: {str(e)}")

    def generate_property_defaults(self, properties: List[Property]) -> str:
        return '\n'.join(f'            .property("{p.name}", {p.default_value})' 
                        for p in properties)

    def generate_constructor_params(self, properties: List[Property]) -> str:
        return ', '.join(f'{p.name}: {p.rust_type}' for p in properties)

    def generate_property_builders(self, properties: List[Property]) -> str:
        return '\n'.join(f'            .property("{p.name}", {p.name})' 
                        for p in properties)

    def generate_debug_fields(self, properties: List[Property]) -> str:
        return '\n'.join(f'            .field("{p.name}", &self.property::<{p.rust_type}>("{p.name}"))'
                        for p in properties)

def main():
    parser = argparse.ArgumentParser(description='Create a new GObject class in Rust')
    parser.add_argument('class_name', help='The class name in PascalCase')
    parser.add_argument('parent_class', help='The parent class name')
    parser.add_argument('--properties', nargs='*', help='Properties in format name:type', default=[])
    parser.add_argument('--signals', nargs='*', help='Signal names, optionally with parameters: name(param:type)', default=[])
    parser.add_argument('--imports', nargs='*', help='Additional imports', default=[])
    parser.add_argument('path', help='Output path for the Rust file')
    
    args = parser.parse_args()

    try:
        # Create generator instance
        generator = RustGObjectGenerator()

        # Generate the code
        rust_code = generator.generate_code(
            args.class_name,
            args.parent_class,
            args.properties,
            args.signals,
            args.imports
        )

        # Ensure output directory exists
        os.makedirs(args.path, exist_ok=True)
        
        # Write to file
        output_path = os.path.join(args.path, f"{args.class_name.lower()}.rs")
        with open(output_path, 'w') as f:
            f.write(rust_code)
            
        print(f"Successfully generated {output_path}")
        
    except Exception as e:
        print(f"Error: {str(e)}", file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    main()
